name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  update-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create app-script-url.js
        run: |
          echo "const APP_SCRIPT_URL = 'https://script.google.com/macros/s/${{ secrets.APP_SCRIPT }}/exec';" > resources/app-script-url.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Change this if your index.html is in a different directory
